"""empty message

Revision ID: 715a06db6fe1
Revises: a87cf4947a6d
Create Date: 2018-02-12 22:09:36.554454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '715a06db6fe1'
down_revision = 'a87cf4947a6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('total', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'total')
    # ### end Alembic commands ###
