"""empty message

Revision ID: a00d7af5beaf
Revises: 1d2685441f18
Create Date: 2018-02-09 19:46:03.992611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a00d7af5beaf'
down_revision = '1d2685441f18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('panels',
    sa.Column('panel_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('width', sa.Numeric(), nullable=False),
    sa.Column('height', sa.Numeric(), nullable=False),
    sa.Column('thickness', sa.Numeric(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('panel_id')
    )
    op.create_table('pedestals',
    sa.Column('pedestal_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('width', sa.Numeric(), nullable=False),
    sa.Column('height', sa.Numeric(), nullable=False),
    sa.Column('depth', sa.Numeric(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('pedestal_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedestals')
    op.drop_table('panels')
    op.drop_table('custom_projects')
    # ### end Alembic commands ###
