"""empty message

Revision ID: e5e74d450857
Revises: 5ca83a02e934
Create Date: 2018-02-12 21:47:53.550941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5e74d450857'
down_revision = '5ca83a02e934'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_projects', sa.Column('p_p_type', sa.String(), nullable=False))
    op.drop_column('custom_projects', 'p_type')
    op.add_column('panels', sa.Column('p_p_type', sa.String(), nullable=False))
    op.drop_column('panels', 'p_type')
    op.add_column('pedestals', sa.Column('p_p_type', sa.String(), nullable=False))
    op.drop_column('pedestals', 'p_type')
    op.add_column('strainer_bars', sa.Column('p_p_type', sa.String(), nullable=False))
    op.drop_column('strainer_bars', 'p_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strainer_bars', sa.Column('p_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('strainer_bars', 'p_p_type')
    op.add_column('pedestals', sa.Column('p_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('pedestals', 'p_p_type')
    op.add_column('panels', sa.Column('p_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('panels', 'p_p_type')
    op.add_column('custom_projects', sa.Column('p_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('custom_projects', 'p_p_type')
    # ### end Alembic commands ###
