"""empty message

Revision ID: f5ec641664e5
Revises: b58becd4afc4
Create Date: 2018-02-11 17:42:29.833460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5ec641664e5'
down_revision = 'b58becd4afc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_projects', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('custom_projects', sa.Column('total', sa.Numeric(), nullable=False))
    op.add_column('panels', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('panels', sa.Column('total', sa.Numeric(), nullable=False))
    op.add_column('pedestals', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('pedestals', sa.Column('total', sa.Numeric(), nullable=False))
    op.add_column('strainer_bars', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('strainer_bars', sa.Column('total', sa.Numeric(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strainer_bars', 'total')
    op.drop_column('strainer_bars', 'quantity')
    op.drop_column('pedestals', 'total')
    op.drop_column('pedestals', 'quantity')
    op.drop_column('panels', 'total')
    op.drop_column('panels', 'quantity')
    op.drop_column('custom_projects', 'total')
    op.drop_column('custom_projects', 'quantity')
    # ### end Alembic commands ###
